### ISSUE TITLE
Pinout for the board is incorrect

### ISSUE THREAD

**Issue by jamescoggan** [theangels/AndroidThings_Thingworx_Demo#1]
Hi,

Is the image with the rapsberry pi pinout correct? it seems to be connected to the 2 5V pins.
Also the data pins seem wrong.
Its also safer to have an i2c shifter to protect the PI, since the arduino output is 5V
Take care!

**Comment by theangels** [comment]
Hi,

Sorry, I fixed the pin problem in the picture.
This project was published at my university level. Maybe the AndroidThings pin was very different from the current pin definition. The project is no longer maintained, but I have fixed the pin problem to avoid misleading.

Finally, thanks for your issueing.
